version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - minor
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
