import { RecentTasksProvider } from "@/components/RecentTasksProvider";
import { TaskEventsProvider } from "@/components/TaskEventsProvider";
import { TaskProvider } from "@/components/TasksProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import { MyTabs } from "@/components/MyTabs";
import ThemeRegistry from "@/components/ThemeRegistry";
import { MyAppBar } from "@/components/MyAppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "worktimer",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <html lang="en">
    <body className={inter.className}>
      <ThemeRegistry>
        <TaskEventsProvider>
          <MyAppBar />
          <RecentTasksProvider>
            <MyTabs />
            <TaskProvider>{children}</TaskProvider>
          </RecentTasksProvider>
        </TaskEventsProvider>
      </ThemeRegistry>
    </body>
  </html>
);

export default RootLayout;
